# Generated by Django 6.0.2 on 2026-03-27 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_resumeupload_ai_confidence_score_and_more'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMatchingCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_job_types', models.JSONField(blank=True, default=list)),
                ('preferred_locations', models.JSONField(blank=True, default=list)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remote_preference', models.CharField(choices=[('any', 'Any'), ('remote_only', 'Remote Only'), ('hybrid', 'Hybrid'), ('onsite', 'On-site Only')], default='any', max_length=20)),
                ('preferred_industries', models.JSONField(blank=True, default=list)),
                ('company_sizes', models.JSONField(blank=True, default=list)),
                ('skill_match_weight', models.FloatField(default=0.4)),
                ('experience_match_weight', models.FloatField(default=0.2)),
                ('education_match_weight', models.FloatField(default=0.1)),
                ('location_match_weight', models.FloatField(default=0.1)),
                ('salary_match_weight', models.FloatField(default=0.2)),
                ('feedback_history', models.JSONField(blank=True, default=list)),
                ('learned_preferences', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('remote', 'Remote')], max_length=50)),
                ('match_score', models.FloatField(help_text='AI-calculated match percentage (0-100)')),
                ('skill_match_score', models.FloatField(blank=True, null=True)),
                ('experience_match_score', models.FloatField(blank=True, null=True)),
                ('education_match_score', models.FloatField(blank=True, null=True)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('match_reasons', models.JSONField(blank=True, default=list)),
                ('improvement_suggestions', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(choices=[('internal', 'Internal Database'), ('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('glassdoor', 'Glassdoor'), ('api', 'External API')], default='internal', max_length=50)),
                ('external_job_id', models.CharField(blank=True, max_length=100)),
                ('application_url', models.URLField(blank=True)),
                ('posted_date', models.DateTimeField(blank=True, null=True)),
                ('is_saved', models.BooleanField(default=False)),
                ('is_applied', models.BooleanField(default=False)),
                ('is_viewed', models.BooleanField(default=False)),
                ('user_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_engine.resumeupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-match_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('liked', 'Liked'), ('disliked', 'Disliked'), ('applied', 'Applied'), ('saved', 'Saved'), ('not_interested', 'Not Interested')], max_length=20)),
                ('feedback_score', models.IntegerField(blank=True, null=True)),
                ('feedback_text', models.TextField(blank=True)),
                ('relevant_factors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobrecommendation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('proficiency_level', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Novice'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Expert')])),
                ('category', models.CharField(choices=[('programming', 'Programming'), ('web_development', 'Web Development'), ('data_science', 'Data Science'), ('cloud_devops', 'Cloud/DevOps'), ('databases', 'Databases'), ('mobile', 'Mobile Development'), ('tools_software', 'Tools/Software'), ('methodologies', 'Methodologies'), ('soft_skills', 'Soft Skills')], max_length=50)),
                ('years_experience', models.FloatField(blank=True, null=True)),
                ('last_used', models.DateField(blank=True, null=True)),
                ('is_preferred', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-proficiency_level', 'skill_name'],
            },
        ),
        migrations.AddIndex(
            model_name='jobrecommendation',
            index=models.Index(fields=['user', '-match_score'], name='jobs_jobrec_user_id_f8175b_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrecommendation',
            index=models.Index(fields=['source'], name='jobs_jobrec_source_7d1b8a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='matchingfeedback',
            unique_together={('user', 'recommendation')},
        ),
        migrations.AlterUniqueTogether(
            name='userprofileskill',
            unique_together={('user', 'skill_name')},
        ),
    ]
