# Generated by Django 6.0.2 on 2026-03-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobmatchingcriteria_jobrecommendation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('programming', 'Programming Languages'), ('web_development', 'Web Development'), ('web_frameworks', 'Web Frameworks'), ('data_science', 'Data Science & Analytics'), ('machine_learning', 'Machine Learning & AI'), ('cloud_devops', 'Cloud & DevOps'), ('databases', 'Databases'), ('mobile_development', 'Mobile Development'), ('software_tools', 'Software Tools'), ('methodologies', 'Methodologies & Practices'), ('soft_skills', 'Soft Skills'), ('business_skills', 'Business Skills'), ('design_skills', 'Design Skills'), ('certifications', 'Certifications')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('synonyms', models.JSONField(blank=True, default=list)),
                ('related_skills', models.JSONField(blank=True, default=list)),
                ('proficiency_levels', models.JSONField(blank=True, default=list)),
                ('typical_years_experience', models.FloatField(blank=True, null=True)),
                ('demand_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3)),
                ('industries', models.JSONField(blank=True, default=list)),
                ('job_titles', models.JSONField(blank=True, default=list)),
                ('technical_weight', models.FloatField(default=1.0)),
                ('business_weight', models.FloatField(default=0.5)),
                ('creative_weight', models.FloatField(default=0.3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category'], name='jobs_skilld_categor_383ec9_idx'), models.Index(fields=['demand_level'], name='jobs_skilld_demand__414db8_idx'), models.Index(fields=['is_active'], name='jobs_skilld_is_acti_274199_idx')],
            },
        ),
    ]
