# Generated by Django 6.0.3 on 2026-04-13 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobpost_jobapplication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='jobapplication',
            name='jobs_jobapp_job_pos_7c6125_idx',
        ),
        migrations.RemoveIndex(
            model_name='jobapplication',
            name='jobs_jobapp_student_e8865a_idx',
        ),
        migrations.DeleteModel(
            name='JobListing',
        ),
        migrations.RemoveField(
            model_name='jobmatchingcriteria',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='jobpost',
            name='jobs_jobpos_job_pro_3e345a_idx',
        ),
        migrations.RemoveIndex(
            model_name='jobpost',
            name='jobs_jobpos_status_b64ac9_idx',
        ),
        migrations.RemoveIndex(
            model_name='jobpost',
            name='jobs_jobpos_created_0aaca1_idx',
        ),
        migrations.RemoveIndex(
            model_name='jobrecommendation',
            name='jobs_jobrec_user_id_f8175b_idx',
        ),
        migrations.RemoveIndex(
            model_name='jobrecommendation',
            name='jobs_jobrec_source_7d1b8a_idx',
        ),
        migrations.RemoveField(
            model_name='matchingfeedback',
            name='recommendation',
        ),
        migrations.AlterUniqueTogether(
            name='matchingfeedback',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='matchingfeedback',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='skilldatabase',
            name='jobs_skilld_categor_383ec9_idx',
        ),
        migrations.RemoveIndex(
            model_name='skilldatabase',
            name='jobs_skilld_demand__414db8_idx',
        ),
        migrations.RemoveIndex(
            model_name='skilldatabase',
            name='jobs_skilld_is_acti_274199_idx',
        ),
        migrations.DeleteModel(
            name='SkillDatabase',
        ),
        migrations.AlterUniqueTogether(
            name='userprofileskill',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userprofileskill',
            name='user',
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='job_post',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='student',
        ),
        migrations.DeleteModel(
            name='JobMatchingCriteria',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='job_provider',
        ),
        migrations.RemoveField(
            model_name='jobrecommendation',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='jobrecommendation',
            name='user',
        ),
        migrations.DeleteModel(
            name='MatchingFeedback',
        ),
        migrations.DeleteModel(
            name='UserProfileSkill',
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
        migrations.DeleteModel(
            name='JobPost',
        ),
        migrations.DeleteModel(
            name='JobRecommendation',
        ),
    ]
