# Generated by Django 6.0.3 on 2026-04-14 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0004_resumeupload_user'),
        ('jobs', '0005_application_job_alter_jobapplication_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobMatchingCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_job_types', models.JSONField(blank=True, default=list)),
                ('preferred_locations', models.JSONField(blank=True, default=list)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remote_preference', models.CharField(choices=[('any', 'Any'), ('remote_only', 'Remote Only'), ('hybrid', 'Hybrid'), ('onsite', 'On-site Only')], default='any', max_length=20)),
                ('preferred_industries', models.JSONField(blank=True, default=list)),
                ('company_sizes', models.JSONField(blank=True, default=list)),
                ('skill_match_weight', models.FloatField(default=0.4)),
                ('experience_match_weight', models.FloatField(default=0.2)),
                ('education_match_weight', models.FloatField(default=0.1)),
                ('location_match_weight', models.FloatField(default=0.1)),
                ('salary_match_weight', models.FloatField(default=0.2)),
                ('feedback_history', models.JSONField(blank=True, default=list)),
                ('learned_preferences', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('required_skills', models.JSONField(default=list, help_text='List of required skills')),
                ('number_of_students_needed', models.PositiveIntegerField(default=1)),
                ('institution', models.CharField(help_text='Institution or Company', max_length=200)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('stipend_salary', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('draft', 'Draft')], default='active', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(blank=True, help_text='Application deadline', null=True)),
                ('job_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_full_name', models.CharField(max_length=200)),
                ('student_department', models.CharField(blank=True, max_length=100)),
                ('student_academic_year', models.CharField(blank=True, max_length=50)),
                ('student_number', models.CharField(blank=True, max_length=50)),
                ('cover_letter', models.TextField(blank=True)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='application_resumes/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Notes from job provider')),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobpost')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='JobRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('remote', 'Remote')], max_length=50)),
                ('match_score', models.FloatField(help_text='AI-calculated match percentage (0-100)')),
                ('skill_match_score', models.FloatField(blank=True, null=True)),
                ('experience_match_score', models.FloatField(blank=True, null=True)),
                ('education_match_score', models.FloatField(blank=True, null=True)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('match_reasons', models.JSONField(blank=True, default=list)),
                ('improvement_suggestions', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(choices=[('internal', 'Internal Database'), ('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('glassdoor', 'Glassdoor'), ('api', 'External API')], default='internal', max_length=50)),
                ('external_job_id', models.CharField(blank=True, max_length=100)),
                ('application_url', models.URLField(blank=True)),
                ('posted_date', models.DateTimeField(blank=True, null=True)),
                ('is_saved', models.BooleanField(default=False)),
                ('is_applied', models.BooleanField(default=False)),
                ('is_viewed', models.BooleanField(default=False)),
                ('user_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_engine.resumeupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-match_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('liked', 'Liked'), ('disliked', 'Disliked'), ('applied', 'Applied'), ('saved', 'Saved'), ('not_interested', 'Not Interested')], max_length=20)),
                ('feedback_score', models.IntegerField(blank=True, null=True)),
                ('feedback_text', models.TextField(blank=True)),
                ('relevant_factors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobrecommendation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkillDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('programming', 'Programming Languages'), ('web_development', 'Web Development'), ('web_frameworks', 'Web Frameworks'), ('data_science', 'Data Science & Analytics'), ('machine_learning', 'Machine Learning & AI'), ('cloud_devops', 'Cloud & DevOps'), ('databases', 'Databases'), ('mobile_development', 'Mobile Development'), ('software_tools', 'Software Tools'), ('methodologies', 'Methodologies & Practices'), ('soft_skills', 'Soft Skills'), ('business_skills', 'Business Skills'), ('design_skills', 'Design Skills'), ('certifications', 'Certifications')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('synonyms', models.JSONField(blank=True, default=list)),
                ('related_skills', models.JSONField(blank=True, default=list)),
                ('proficiency_levels', models.JSONField(blank=True, default=list)),
                ('typical_years_experience', models.FloatField(blank=True, null=True)),
                ('demand_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3)),
                ('industries', models.JSONField(blank=True, default=list)),
                ('job_titles', models.JSONField(blank=True, default=list)),
                ('technical_weight', models.FloatField(default=1.0)),
                ('business_weight', models.FloatField(default=0.5)),
                ('creative_weight', models.FloatField(default=0.3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category'], name='jobs_skilld_categor_383ec9_idx'), models.Index(fields=['demand_level'], name='jobs_skilld_demand__414db8_idx'), models.Index(fields=['is_active'], name='jobs_skilld_is_acti_274199_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfileSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('proficiency_level', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Novice'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Expert')])),
                ('category', models.CharField(choices=[('programming', 'Programming'), ('web_development', 'Web Development'), ('data_science', 'Data Science'), ('cloud_devops', 'Cloud/DevOps'), ('databases', 'Databases'), ('mobile', 'Mobile Development'), ('tools_software', 'Tools/Software'), ('methodologies', 'Methodologies'), ('soft_skills', 'Soft Skills')], max_length=50)),
                ('years_experience', models.FloatField(blank=True, null=True)),
                ('last_used', models.DateField(blank=True, null=True)),
                ('is_preferred', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-proficiency_level', 'skill_name'],
            },
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['job_provider', '-created_at'], name='jobs_jobpos_job_pro_3e345a_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['status'], name='jobs_jobpos_status_b64ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['-created_at'], name='jobs_jobpos_created_0aaca1_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job_post', 'status'], name='jobs_jobapp_job_pos_7c6125_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['student', '-applied_at'], name='jobs_jobapp_student_e8865a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('job_post', 'student')},
        ),
        migrations.AddIndex(
            model_name='jobrecommendation',
            index=models.Index(fields=['user', '-match_score'], name='jobs_jobrec_user_id_f8175b_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrecommendation',
            index=models.Index(fields=['source'], name='jobs_jobrec_source_7d1b8a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='matchingfeedback',
            unique_together={('user', 'recommendation')},
        ),
        migrations.AlterUniqueTogether(
            name='userprofileskill',
            unique_together={('user', 'skill_name')},
        ),
    ]
