# Generated by Django 6.0.3 on 2026-04-14 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_completion', models.IntegerField(default=0, help_text='Percentage of profile completion (0-100)')),
                ('assessment_completed', models.BooleanField(default=False)),
                ('career_matches', models.IntegerField(default=0)),
                ('skills_analyzed', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('job_provider', 'Job Provider')], default='student', max_length=20)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('extracted_skills', models.TextField(blank=True, help_text='JSON string of extracted skills')),
                ('institution', models.CharField(blank=True, help_text='Institution or Company name', max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('professional_description', models.TextField(blank=True, help_text='Short professional description')),
                ('is_verified', models.BooleanField(default=False, help_text='For job providers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('proficiency_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('source', models.CharField(choices=[('resume', 'Resume Extraction'), ('questionnaire', 'Questionnaire'), ('manual', 'Manual Entry')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'skill_name')},
            },
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
