"""
Comprehensive skills database for AI resume analysis
Contains all possible skills with categories, synonyms, and metadata
"""

COMPREHENSIVE_SKILLS_DATABASE = [
    # Programming Languages
    {"name": "Python", "category": "programming", "synonyms": ["python3", "py"], "demand_level": 5, "industries": ["tech", "finance", "healthcare", "science"]},
    {"name": "JavaScript", "category": "programming", "synonyms": ["js", "javascript", "ecmascript"], "demand_level": 5, "industries": ["tech", "web", "mobile"]},
    {"name": "Java", "category": "programming", "synonyms": ["java", "jvm"], "demand_level": 4, "industries": ["enterprise", "finance", "android"]},
    {"name": "TypeScript", "category": "programming", "synonyms": ["ts", "typescript"], "demand_level": 4, "industries": ["tech", "web", "mobile"]},
    {"name": "C++", "category": "programming", "synonyms": ["cpp", "c++"], "demand_level": 4, "industries": ["gaming", "systems", "embedded"]},
    {"name": "C#", "category": "programming", "synonyms": ["csharp", "c#"], "demand_level": 4, "industries": ["enterprise", "gaming", "windows"]},
    {"name": "Go", "category": "programming", "synonyms": ["golang", "go"], "demand_level": 4, "industries": ["tech", "cloud", "infrastructure"]},
    {"name": "Rust", "category": "programming", "synonyms": ["rust", "rs"], "demand_level": 3, "industries": ["systems", "blockchain", "performance"]},
    {"name": "Ruby", "category": "programming", "synonyms": ["ruby", "rb"], "demand_level": 3, "industries": ["web", "startups"]},
    {"name": "PHP", "category": "programming", "synonyms": ["php"], "demand_level": 3, "industries": ["web", "cms", "ecommerce"]},
    {"name": "Swift", "category": "programming", "synonyms": ["swift"], "demand_level": 4, "industries": ["mobile", "ios"]},
    {"name": "Kotlin", "category": "programming", "synonyms": ["kotlin", "kt"], "demand_level": 4, "industries": ["mobile", "android", "backend"]},
    {"name": "R", "category": "programming", "synonyms": ["r", "rstats"], "demand_level": 4, "industries": ["data", "research", "academia"]},
    {"name": "MATLAB", "category": "programming", "synonyms": ["matlab"], "demand_level": 3, "industries": ["engineering", "research", "academia"]},
    {"name": "Scala", "category": "programming", "synonyms": ["scala"], "demand_level": 3, "industries": ["bigdata", "fintech", "enterprise"]},
    {"name": "Perl", "category": "programming", "synonyms": ["perl"], "demand_level": 2, "industries": ["legacy", "sysadmin"]},
    {"name": "SQL", "category": "programming", "synonyms": ["sql", "structured query language"], "demand_level": 5, "industries": ["all"]},
    {"name": "Bash", "category": "programming", "synonyms": ["bash", "shell", "sh"], "demand_level": 4, "industries": ["devops", "sysadmin", "tech"]},
    {"name": "PowerShell", "category": "programming", "synonyms": ["powershell", "ps"], "demand_level": 3, "industries": ["windows", "sysadmin", "enterprise"]},
    
    # Web Development
    {"name": "HTML", "category": "web_development", "synonyms": ["html", "html5", "markup"], "demand_level": 5, "industries": ["web", "tech"]},
    {"name": "CSS", "category": "web_development", "synonyms": ["css", "css3", "stylesheets"], "demand_level": 5, "industries": ["web", "tech"]},
    {"name": "SASS", "category": "web_development", "synonyms": ["sass", "scss"], "demand_level": 4, "industries": ["web", "tech"]},
    {"name": "LESS", "category": "web_development", "synonyms": ["less"], "demand_level": 3, "industries": ["web", "tech"]},
    {"name": "Tailwind CSS", "category": "web_development", "synonyms": ["tailwind", "tailwindcss"], "demand_level": 4, "industries": ["web", "tech"]},
    {"name": "Bootstrap", "category": "web_development", "synonyms": ["bootstrap", "bootstrap4", "bootstrap5"], "demand_level": 4, "industries": ["web", "tech"]},
    {"name": "Material UI", "category": "web_development", "synonyms": ["mui", "material-ui"], "demand_level": 4, "industries": ["web", "tech"]},
    {"name": "Ant Design", "category": "web_development", "synonyms": ["antd", "antdesign"], "demand_level": 4, "industries": ["web", "tech"]},
    {"name": "Chakra UI", "category": "web_development", "synonyms": ["chakra", "chakra-ui"], "demand_level": 3, "industries": ["web", "tech"]},
    {"name": "Styled Components", "category": "web_development", "synonyms": ["styled-components"], "demand_level": 4, "industries": ["web", "tech"]},
    {"name": "Emotion", "category": "web_development", "synonyms": ["emotion"], "demand_level": 3, "industries": ["web", "tech"]},
    {"name": "CSS-in-JS", "category": "web_development", "synonyms": ["css-in-js"], "demand_level": 3, "industries": ["web", "tech"]},
    {"name": "Responsive Design", "category": "web_development", "synonyms": ["responsive", "mobile-first"], "demand_level": 5, "industries": ["web", "tech"]},
    {"name": "Progressive Web Apps", "category": "web_development", "synonyms": ["pwa", "progressive web apps"], "demand_level": 4, "industries": ["web", "tech"]},
    {"name": "Web Accessibility", "category": "web_development", "synonyms": ["a11y", "accessibility", "wcag"], "demand_level": 4, "industries": ["web", "tech"]},
    {"name": "Cross-browser Compatibility", "category": "web_development", "synonyms": ["cross-browser"], "demand_level": 4, "industries": ["web", "tech"]},
    
    # Web Frameworks
    {"name": "React", "category": "web_frameworks", "synonyms": ["react", "reactjs"], "demand_level": 5, "industries": ["web", "tech", "mobile"]},
    {"name": "Angular", "category": "web_frameworks", "synonyms": ["angular", "angularjs"], "demand_level": 4, "industries": ["web", "tech", "enterprise"]},
    {"name": "Vue.js", "category": "web_frameworks", "synonyms": ["vue", "vuejs"], "demand_level": 4, "industries": ["web", "tech"]},
    {"name": "Next.js", "category": "web_frameworks", "synonyms": ["next", "nextjs"], "demand_level": 4, "industries": ["web", "tech"]},
    {"name": "Gatsby", "category": "web_frameworks", "synonyms": ["gatsby"], "demand_level": 3, "industries": ["web", "cms"]},
    {"name": "Nuxt.js", "category": "web_frameworks", "synonyms": ["nuxt", "nuxtjs"], "demand_level": 3, "industries": ["web", "tech"]},
    {"name": "Svelte", "category": "web_frameworks", "synonyms": ["svelte"], "demand_level": 3, "industries": ["web", "tech"]},
    {"name": "Solid.js", "category": "web_frameworks", "synonyms": ["solid", "solidjs"], "demand_level": 2, "industries": ["web", "tech"]},
    {"name": "Alpine.js", "category": "web_frameworks", "synonyms": ["alpine", "alpinejs"], "demand_level": 3, "industries": ["web", "tech"]},
    {"name": "Backbone.js", "category": "web_frameworks", "synonyms": ["backbone", "backbonejs"], "demand_level": 2, "industries": ["web", "legacy"]},
    {"name": "Ember.js", "category": "web_frameworks", "synonyms": ["ember", "emberjs"], "demand_level": 2, "industries": ["web", "tech"]},
    {"name": "Django", "category": "web_frameworks", "synonyms": ["django"], "demand_level": 4, "industries": ["web", "tech", "python"]},
    {"name": "Flask", "category": "web_frameworks", "synonyms": ["flask"], "demand_level": 4, "industries": ["web", "tech", "python"]},
    {"name": "FastAPI", "category": "web_frameworks", "synonyms": ["fastapi"], "demand_level": 4, "industries": ["web", "tech", "python"]},
    {"name": "Express.js", "category": "web_frameworks", "synonyms": ["express", "expressjs"], "demand_level": 5, "industries": ["web", "tech", "node"]},
    {"name": "Koa.js", "category": "web_frameworks", "synonyms": ["koa", "koajs"], "demand_level": 3, "industries": ["web", "tech", "node"]},
    {"name": "NestJS", "category": "web_frameworks", "synonyms": ["nestjs"], "demand_level": 4, "industries": ["web", "tech", "node"]},
    {"name": "Ruby on Rails", "category": "web_frameworks", "synonyms": ["rails", "ror"], "demand_level": 4, "industries": ["web", "tech", "ruby"]},
    {"name": "Laravel", "category": "web_frameworks", "synonyms": ["laravel"], "demand_level": 4, "industries": ["web", "tech", "php"]},
    {"name": "Symfony", "category": "web_frameworks", "synonyms": ["symfony"], "demand_level": 3, "industries": ["web", "tech", "php"]},
    {"name": "Spring Boot", "category": "web_frameworks", "synonyms": ["spring", "springboot"], "demand_level": 4, "industries": ["web", "tech", "java"]},
    {"name": "ASP.NET Core", "category": "web_frameworks", "synonyms": ["aspnet", "dotnet"], "demand_level": 4, "industries": ["web", "tech", "enterprise"]},
    
    # Data Science & Analytics
    {"name": "Data Science", "category": "data_science", "synonyms": ["datascience", "analytics"], "demand_level": 5, "industries": ["tech", "finance", "healthcare"]},
    {"name": "Data Analysis", "category": "data_science", "synonyms": ["dataanalysis", "analytics"], "demand_level": 5, "industries": ["all"]},
    {"name": "Statistics", "category": "data_science", "synonyms": ["stats", "statistical analysis"], "demand_level": 4, "industries": ["research", "finance", "healthcare"]},
    {"name": "Pandas", "category": "data_science", "synonyms": ["pandas"], "demand_level": 5, "industries": ["data", "tech", "finance"]},
    {"name": "NumPy", "category": "data_science", "synonyms": ["numpy"], "demand_level": 5, "industries": ["data", "tech", "science"]},
    {"name": "Jupyter", "category": "data_science", "synonyms": ["jupyter", "notebook"], "demand_level": 5, "industries": ["data", "research", "education"]},
    {"name": "Tableau", "category": "data_science", "synonyms": ["tableau"], "demand_level": 4, "industries": ["business", "analytics", "data"]},
    {"name": "Power BI", "category": "data_science", "synonyms": ["powerbi", "power bi"], "demand_level": 4, "industries": ["business", "analytics", "data"]},
    {"name": "Excel", "category": "data_science", "synonyms": ["excel", "microsoft excel"], "demand_level": 5, "industries": ["business", "finance", "all"]},
    {"name": "Google Sheets", "category": "data_science", "synonyms": ["sheets", "google sheets"], "demand_level": 4, "industries": ["business", "collaboration"]},
    {"name": "Apache Spark", "category": "data_science", "synonyms": ["spark"], "demand_level": 4, "industries": ["bigdata", "tech", "finance"]},
    {"name": "Apache Hadoop", "category": "data_science", "synonyms": ["hadoop"], "demand_level": 3, "industries": ["bigdata", "enterprise"]},
    {"name": "Apache Kafka", "category": "data_science", "synonyms": ["kafka"], "demand_level": 4, "industries": ["data", "tech", "finance"]},
    {"name": "Apache Flink", "category": "data_science", "synonyms": ["flink"], "demand_level": 3, "industries": ["data", "tech"]},
    {"name": "Elasticsearch", "category": "data_science", "synonyms": ["elasticsearch", "elastic"], "demand_level": 4, "industries": ["search", "data", "tech"]},
    {"name": "Kibana", "category": "data_science", "synonyms": ["kibana"], "demand_level": 4, "industries": ["data", "visualization", "tech"]},
    {"name": "Logstash", "category": "data_science", "synonyms": ["logstash"], "demand_level": 3, "industries": ["data", "logs", "tech"]},
    {"name": "Data Visualization", "category": "data_science", "synonyms": ["dataviz", "visualization"], "demand_level": 4, "industries": ["data", "analytics", "tech"]},
    {"name": "Business Intelligence", "category": "data_science", "synonyms": ["bi", "business intelligence"], "demand_level": 4, "industries": ["business", "analytics", "data"]},
    
    # Machine Learning & AI
    {"name": "Machine Learning", "category": "machine_learning", "synonyms": ["ml", "machinelearning"], "demand_level": 5, "industries": ["tech", "finance", "healthcare"]},
    {"name": "Deep Learning", "category": "machine_learning", "synonyms": ["dl", "deeplearning"], "demand_level": 5, "industries": ["tech", "research", "automotive"]},
    {"name": "Artificial Intelligence", "category": "machine_learning", "synonyms": ["ai", "artificial intelligence"], "demand_level": 5, "industries": ["tech", "research", "all"]},
    {"name": "TensorFlow", "category": "machine_learning", "synonyms": ["tensorflow", "tf"], "demand_level": 5, "industries": ["tech", "research", "ml"]},
    {"name": "PyTorch", "category": "machine_learning", "synonyms": ["pytorch"], "demand_level": 5, "industries": ["tech", "research", "ml"]},
    {"name": "Keras", "category": "machine_learning", "synonyms": ["keras"], "demand_level": 4, "industries": ["ml", "tech", "research"]},
    {"name": "Scikit-learn", "category": "machine_learning", "synonyms": ["sklearn", "scikit-learn"], "demand_level": 5, "industries": ["ml", "data", "tech"]},
    {"name": "Natural Language Processing", "category": "machine_learning", "synonyms": ["nlp", "natural language processing"], "demand_level": 5, "industries": ["tech", "research", "healthcare"]},
    {"name": "Computer Vision", "category": "machine_learning", "synonyms": ["cv", "computer vision"], "demand_level": 5, "industries": ["tech", "automotive", "healthcare"]},
    {"name": "OpenCV", "category": "machine_learning", "synonyms": ["opencv"], "demand_level": 4, "industries": ["cv", "tech", "robotics"]},
    {"name": "Reinforcement Learning", "category": "machine_learning", "synonyms": ["rl", "reinforcement learning"], "demand_level": 4, "industries": ["research", "gaming", "robotics"]},
    {"name": "Neural Networks", "category": "machine_learning", "synonyms": ["nn", "neural networks"], "demand_level": 5, "industries": ["ml", "research", "tech"]},
    {"name": "BERT", "category": "machine_learning", "synonyms": ["bert"], "demand_level": 4, "industries": ["nlp", "tech", "research"]},
    {"name": "GPT", "category": "machine_learning", "synonyms": ["gpt", "chatgpt"], "demand_level": 5, "industries": ["nlp", "tech", "research"]},
    {"name": "Transformers", "category": "machine_learning", "synonyms": ["transformers", "attention"], "demand_level": 5, "industries": ["nlp", "tech", "research"]},
    {"name": "XGBoost", "category": "machine_learning", "synonyms": ["xgboost"], "demand_level": 4, "industries": ["ml", "data", "tech"]},
    {"name": "LightGBM", "category": "machine_learning", "synonyms": ["lightgbm"], "demand_level": 4, "industries": ["ml", "data", "tech"]},
    {"name": "CatBoost", "category": "machine_learning", "synonyms": ["catboost"], "demand_level": 3, "industries": ["ml", "data", "tech"]},
    {"name": "MLflow", "category": "machine_learning", "synonyms": ["mlflow"], "demand_level": 3, "industries": ["ml", "mlops", "tech"]},
    {"name": "Kubeflow", "category": "machine_learning", "synonyms": ["kubeflow"], "demand_level": 3, "industries": ["ml", "mlops", "tech"]},
    
    # Cloud & DevOps
    {"name": "Amazon Web Services", "category": "cloud_devops", "synonyms": ["aws", "amazon cloud"], "demand_level": 5, "industries": ["tech", "all"]},
    {"name": "Microsoft Azure", "category": "cloud_devops", "synonyms": ["azure", "microsoft cloud"], "demand_level": 5, "industries": ["tech", "enterprise", "all"]},
    {"name": "Google Cloud Platform", "category": "cloud_devops", "synonyms": ["gcp", "google cloud"], "demand_level": 4, "industries": ["tech", "data", "all"]},
    {"name": "Docker", "category": "cloud_devops", "synonyms": ["docker", "containers"], "demand_level": 5, "industries": ["tech", "devops", "all"]},
    {"name": "Kubernetes", "category": "cloud_devops", "synonyms": ["kubernetes", "k8s"], "demand_level": 5, "industries": ["tech", "devops", "all"]},
    {"name": "Jenkins", "category": "cloud_devops", "synonyms": ["jenkins"], "demand_level": 4, "industries": ["devops", "tech", "enterprise"]},
    {"name": "Git", "category": "cloud_devops", "synonyms": ["git", "version control"], "demand_level": 5, "industries": ["tech", "all"]},
    {"name": "GitHub", "category": "cloud_devops", "synonyms": ["github"], "demand_level": 5, "industries": ["tech", "all"]},
    {"name": "GitLab", "category": "cloud_devops", "synonyms": ["gitlab"], "demand_level": 4, "industries": ["tech", "devops"]},
    {"name": "Bitbucket", "category": "cloud_devops", "synonyms": ["bitbucket"], "demand_level": 3, "industries": ["tech", "enterprise"]},
    {"name": "CI/CD", "category": "cloud_devops", "synonyms": ["cicd", "continuous integration", "continuous deployment"], "demand_level": 5, "industries": ["tech", "devops", "all"]},
    {"name": "Terraform", "category": "cloud_devops", "synonyms": ["terraform", "iac"], "demand_level": 5, "industries": ["tech", "devops", "cloud"]},
    {"name": "Ansible", "category": "cloud_devops", "synonyms": ["ansible", "automation"], "demand_level": 4, "industries": ["devops", "tech", "enterprise"]},
    {"name": "Puppet", "category": "cloud_devops", "synonyms": ["puppet"], "demand_level": 3, "industries": ["devops", "enterprise"]},
    {"name": "Chef", "category": "cloud_devops", "synonyms": ["chef"], "demand_level": 3, "industries": ["devops", "enterprise"]},
    {"name": "Prometheus", "category": "cloud_devops", "synonyms": ["prometheus", "monitoring"], "demand_level": 4, "industries": ["devops", "tech", "monitoring"]},
    {"name": "Grafana", "category": "cloud_devops", "synonyms": ["grafana", "monitoring", "visualization"], "demand_level": 4, "industries": ["devops", "tech", "monitoring"]},
    {"name": "ELK Stack", "category": "cloud_devops", "synonyms": ["elk", "elasticsearch", "logstash", "kibana"], "demand_level": 4, "industries": ["devops", "tech", "logging"]},
    {"name": "Nginx", "category": "cloud_devops", "synonyms": ["nginx"], "demand_level": 4, "industries": ["web", "devops", "tech"]},
    {"name": "Apache", "category": "cloud_devops", "synonyms": ["apache", "httpd"], "demand_level": 4, "industries": ["web", "devops", "tech"]},
    {"name": "Linux", "category": "cloud_devops", "synonyms": ["linux", "ubuntu", "centos", "redhat"], "demand_level": 5, "industries": ["tech", "devops", "all"]},
    {"name": "Ubuntu", "category": "cloud_devops", "synonyms": ["ubuntu"], "demand_level": 4, "industries": ["tech", "devops", "linux"]},
    {"name": "CentOS", "category": "cloud_devops", "synonyms": ["centos"], "demand_level": 3, "industries": ["tech", "devops", "linux"]},
    {"name": "Red Hat", "category": "cloud_devops", "synonyms": ["redhat", "rhel"], "demand_level": 3, "industries": ["tech", "enterprise", "linux"]},
    {"name": "Windows Server", "category": "cloud_devops", "synonyms": ["windows server"], "demand_level": 3, "industries": ["enterprise", "tech"]},
    {"name": "System Administration", "category": "cloud_devops", "synonyms": ["sysadmin", "system administration"], "demand_level": 4, "industries": ["tech", "it", "all"]},
    {"name": "Network Administration", "category": "cloud_devops", "synonyms": ["networking", "network admin"], "demand_level": 4, "industries": ["tech", "it", "all"]},
    {"name": "Security", "category": "cloud_devops", "synonyms": ["cybersecurity", "infosec"], "demand_level": 5, "industries": ["tech", "finance", "all"]},
    
    # Databases
    {"name": "PostgreSQL", "category": "databases", "synonyms": ["postgresql", "postgres"], "demand_level": 5, "industries": ["tech", "all"]},
    {"name": "MySQL", "category": "databases", "synonyms": ["mysql"], "demand_level": 5, "industries": ["tech", "web", "all"]},
    {"name": "MongoDB", "category": "databases", "synonyms": ["mongodb", "mongo"], "demand_level": 4, "industries": ["tech", "web", "nosql"]},
    {"name": "Redis", "category": "databases", "synonyms": ["redis"], "demand_level": 4, "industries": ["tech", "caching", "nosql"]},
    {"name": "Elasticsearch", "category": "databases", "synonyms": ["elasticsearch", "elastic"], "demand_level": 4, "industries": ["search", "data", "tech"]},
    {"name": "Cassandra", "category": "databases", "synonyms": ["cassandra"], "demand_level": 3, "industries": ["bigdata", "nosql", "tech"]},
    {"name": "Oracle", "category": "databases", "synonyms": ["oracle", "oracle database"], "demand_level": 4, "industries": ["enterprise", "finance", "tech"]},
    {"name": "SQL Server", "category": "databases", "synonyms": ["sql server", "mssql"], "demand_level": 4, "industries": ["enterprise", "windows", "tech"]},
    {"name": "SQLite", "category": "databases", "synonyms": ["sqlite"], "demand_level": 3, "industries": ["mobile", "embedded", "tech"]},
    {"name": "Firebase", "category": "databases", "synonyms": ["firebase"], "demand_level": 4, "industries": ["mobile", "web", "tech"]},
    {"name": "Supabase", "category": "databases", "synonyms": ["supabase"], "demand_level": 3, "industries": ["web", "tech", "startup"]},
    {"name": "DynamoDB", "category": "databases", "synonyms": ["dynamodb"], "demand_level": 4, "industries": ["aws", "nosql", "tech"]},
    {"name": "Couchbase", "category": "databases", "synonyms": ["couchbase"], "demand_level": 3, "industries": ["nosql", "tech"]},
    {"name": "Neo4j", "category": "databases", "synonyms": ["neo4j"], "demand_level": 3, "industries": ["graph", "tech"]},
    {"name": "InfluxDB", "category": "databases", "synonyms": ["influxdb"], "demand_level": 3, "industries": ["timeseries", "iot", "tech"]},
    {"name": "MariaDB", "category": "databases", "synonyms": ["mariadb"], "demand_level": 3, "industries": ["tech", "web", "mysql"]},
    {"name": "Percona", "category": "databases", "synonyms": ["percona"], "demand_level": 2, "industries": ["tech", "mysql", "performance"]},
    {"name": "Database Administration", "category": "databases", "synonyms": ["dba", "database admin"], "demand_level": 4, "industries": ["tech", "enterprise", "all"]},
    {"name": "Database Design", "category": "databases", "synonyms": ["database design", "schema design"], "demand_level": 4, "industries": ["tech", "all"]},
    {"name": "NoSQL", "category": "databases", "synonyms": ["nosql", "document database"], "demand_level": 4, "industries": ["tech", "bigdata", "all"]},
    {"name": "NewSQL", "category": "databases", "synonyms": ["newsql"], "demand_level": 3, "industries": ["tech", "database"]},
    
    # Mobile Development
    {"name": "iOS", "category": "mobile_development", "synonyms": ["ios", "iphone", "ipad"], "demand_level": 4, "industries": ["mobile", "tech"]},
    {"name": "Android", "category": "mobile_development", "synonyms": ["android"], "demand_level": 4, "industries": ["mobile", "tech"]},
    {"name": "React Native", "category": "mobile_development", "synonyms": ["react native"], "demand_level": 4, "industries": ["mobile", "tech"]},
    {"name": "Flutter", "category": "mobile_development", "synonyms": ["flutter"], "demand_level": 4, "industries": ["mobile", "tech"]},
    {"name": "Xamarin", "category": "mobile_development", "synonyms": ["xamarin"], "demand_level": 3, "industries": ["mobile", "tech", "enterprise"]},
    {"name": "Cordova", "category": "mobile_development", "synonyms": ["cordova", "phonegap"], "demand_level": 2, "industries": ["mobile", "hybrid"]},
    {"name": "Ionic", "category": "mobile_development", "synonyms": ["ionic"], "demand_level": 3, "industries": ["mobile", "hybrid", "tech"]},
    {"name": "Unity", "category": "mobile_development", "synonyms": ["unity"], "demand_level": 4, "industries": ["gaming", "mobile", "ar"]},
    {"name": "Mobile Development", "category": "mobile_development", "synonyms": ["mobile", "app development"], "demand_level": 4, "industries": ["mobile", "tech"]},
    {"name": "SwiftUI", "category": "mobile_development", "synonyms": ["swiftui"], "demand_level": 3, "industries": ["mobile", "ios"]},
    {"name": "Jetpack Compose", "category": "mobile_development", "synonyms": ["jetpack compose"], "demand_level": 3, "industries": ["mobile", "android"]},
    {"name": "React Navigation", "category": "mobile_development", "synonyms": ["react navigation"], "demand_level": 3, "industries": ["mobile", "react native"]},
    {"name": "Mobile UI/UX", "category": "mobile_development", "synonyms": ["mobile ui", "mobile ux"], "demand_level": 4, "industries": ["mobile", "tech"]},
    
    # Software Tools
    {"name": "Jira", "category": "software_tools", "synonyms": ["jira", "atlassian"], "demand_level": 5, "industries": ["tech", "enterprise", "all"]},
    {"name": "Confluence", "category": "software_tools", "synonyms": ["confluence", "atlassian"], "demand_level": 4, "industries": ["tech", "enterprise", "all"]},
    {"name": "Slack", "category": "software_tools", "synonyms": ["slack"], "demand_level": 5, "industries": ["tech", "collaboration", "all"]},
    {"name": "Microsoft Office", "category": "software_tools", "synonyms": ["office", "microsoft office"], "demand_level": 5, "industries": ["business", "all"]},
    {"name": "Excel", "category": "software_tools", "synonyms": ["excel", "microsoft excel"], "demand_level": 5, "industries": ["business", "finance", "all"]},
    {"name": "PowerPoint", "category": "software_tools", "synonyms": ["powerpoint", "ppt"], "demand_level": 5, "industries": ["business", "presentation", "all"]},
    {"name": "Word", "category": "software_tools", "synonyms": ["word", "microsoft word"], "demand_level": 5, "industries": ["business", "documentation", "all"]},
    {"name": "Outlook", "category": "software_tools", "synonyms": ["outlook", "microsoft outlook"], "demand_level": 4, "industries": ["business", "email", "all"]},
    {"name": "Teams", "category": "software_tools", "synonyms": ["teams", "microsoft teams"], "demand_level": 5, "industries": ["business", "collaboration", "all"]},
    {"name": "Zoom", "category": "software_tools", "synonyms": ["zoom"], "demand_level": 5, "industries": ["business", "communication", "all"]},
    {"name": "Figma", "category": "software_tools", "synonyms": ["figma"], "demand_level": 5, "industries": ["design", "tech", "product"]},
    {"name": "Sketch", "category": "software_tools", "synonyms": ["sketch"], "demand_level": 4, "industries": ["design", "tech", "product"]},
    {"name": "Adobe Creative Suite", "category": "software_tools", "synonyms": ["adobe", "creative suite"], "demand_level": 4, "industries": ["design", "creative", "marketing"]},
    {"name": "Photoshop", "category": "software_tools", "synonyms": ["photoshop", "adobe photoshop"], "demand_level": 4, "industries": ["design", "creative", "marketing"]},
    {"name": "Illustrator", "category": "software_tools", "synonyms": ["illustrator", "adobe illustrator"], "demand_level": 4, "industries": ["design", "creative", "marketing"]},
    {"name": "InDesign", "category": "software_tools", "synonyms": ["indesign", "adobe indesign"], "demand_level": 3, "industries": ["design", "publishing", "marketing"]},
    {"name": "Premiere Pro", "category": "software_tools", "synonyms": ["premiere", "adobe premiere"], "demand_level": 3, "industries": ["video", "creative", "marketing"]},
    {"name": "After Effects", "category": "software_tools", "synonyms": ["after effects", "adobe after effects"], "demand_level": 3, "industries": ["video", "creative", "marketing"]},
    {"name": "VS Code", "category": "software_tools", "synonyms": ["vscode", "visual studio code"], "demand_level": 5, "industries": ["tech", "development", "all"]},
    {"name": "IntelliJ IDEA", "category": "software_tools", "synonyms": ["intellij", "idea"], "demand_level": 4, "industries": ["tech", "development", "java"]},
    {"name": "Eclipse", "category": "software_tools", "synonyms": ["eclipse"], "demand_level": 3, "industries": ["tech", "development", "java"]},
    {"name": "Sublime Text", "category": "software_tools", "synonyms": ["sublime"], "demand_level": 3, "industries": ["tech", "development"]},
    {"name": "Atom", "category": "software_tools", "synonyms": ["atom"], "demand_level": 2, "industries": ["tech", "development"]},
    {"name": "Vim", "category": "software_tools", "synonyms": ["vim", "vi"], "demand_level": 3, "industries": ["tech", "development", "linux"]},
    {"name": "Emacs", "category": "software_tools", "synonyms": ["emacs"], "demand_level": 2, "industries": ["tech", "development", "linux"]},
    {"name": "Postman", "category": "software_tools", "synonyms": ["postman"], "demand_level": 4, "industries": ["tech", "api", "development"]},
    {"name": "Insomnia", "category": "software_tools", "synonyms": ["insomnia"], "demand_level": 3, "industries": ["tech", "api", "development"]},
    {"name": "Docker Desktop", "category": "software_tools", "synonyms": ["docker desktop"], "demand_level": 4, "industries": ["tech", "devops", "development"]},
    {"name": "VirtualBox", "category": "software_tools", "synonyms": ["virtualbox"], "demand_level": 3, "industries": ["tech", "virtualization"]},
    {"name": "VMware", "category": "software_tools", "synonyms": ["vmware"], "demand_level": 3, "industries": ["tech", "virtualization", "enterprise"]},
    
    # Methodologies & Practices
    {"name": "Agile", "category": "methodologies", "synonyms": ["agile", "scrum", "kanban"], "demand_level": 5, "industries": ["tech", "software", "all"]},
    {"name": "Scrum", "category": "methodologies", "synonyms": ["scrum"], "demand_level": 5, "industries": ["tech", "software", "all"]},
    {"name": "Kanban", "category": "methodologies", "synonyms": ["kanban"], "demand_level": 4, "industries": ["tech", "software", "all"]},
    {"name": "Waterfall", "category": "methodologies", "synonyms": ["waterfall"], "demand_level": 3, "industries": ["software", "enterprise"]},
    {"name": "Lean", "category": "methodologies", "synonyms": ["lean"], "demand_level": 4, "industries": ["manufacturing", "software", "all"]},
    {"name": "Six Sigma", "category": "methodologies", "synonyms": ["six sigma", "6sigma"], "demand_level": 3, "industries": ["manufacturing", "quality", "enterprise"]},
    {"name": "PRINCE2", "category": "methodologies", "synonyms": ["prince2"], "demand_level": 3, "industries": ["project management", "enterprise"]},
    {"name": "PMP", "category": "methodologies", "synonyms": ["pmp", "project management"], "demand_level": 4, "industries": ["project management", "all"]},
    {"name": "ITIL", "category": "methodologies", "synonyms": ["itil"], "demand_level": 3, "industries": ["it", "service management"]},
    {"name": "DevOps", "category": "methodologies", "synonyms": ["devops"], "demand_level": 5, "industries": ["tech", "software", "all"]},
    {"name": "TDD", "category": "methodologies", "synonyms": ["tdd", "test driven development"], "demand_level": 4, "industries": ["tech", "software", "quality"]},
    {"name": "BDD", "category": "methodologies", "synonyms": ["bdd", "behavior driven development"], "demand_level": 3, "industries": ["tech", "software", "quality"]},
    {"name": "Microservices", "category": "methodologies", "synonyms": ["microservices"], "demand_level": 5, "industries": ["tech", "software", "architecture"]},
    {"name": "Serverless", "category": "methodologies", "synonyms": ["serverless", "faas"], "demand_level": 4, "industries": ["tech", "cloud", "architecture"]},
    {"name": "Domain Driven Design", "category": "methodologies", "synonyms": ["ddd", "domain driven design"], "demand_level": 3, "industries": ["tech", "software", "architecture"]},
    {"name": "Test Automation", "category": "methodologies", "synonyms": ["test automation", "automation testing"], "demand_level": 4, "industries": ["tech", "quality", "software"]},
    {"name": "Continuous Integration", "category": "methodologies", "synonyms": ["ci", "continuous integration"], "demand_level": 5, "industries": ["tech", "devops", "software"]},
    {"name": "Continuous Deployment", "category": "methodologies", "synonyms": ["cd", "continuous deployment"], "demand_level": 5, "industries": ["tech", "devops", "software"]},
    {"name": "Code Review", "category": "methodologies", "synonyms": ["code review", "peer review"], "demand_level": 4, "industries": ["tech", "software", "quality"]},
    {"name": "Pair Programming", "category": "methodologies", "synonyms": ["pair programming"], "demand_level": 3, "industries": ["tech", "software", "collaboration"]},
    {"name": "Software Architecture", "category": "methodologies", "synonyms": ["architecture", "software architecture"], "demand_level": 5, "industries": ["tech", "software", "all"]},
    {"name": "System Design", "category": "methodologies", "synonyms": ["system design", "system architecture"], "demand_level": 5, "industries": ["tech", "software", "all"]},
    {"name": "API Design", "category": "methodologies", "synonyms": ["api design", "rest api"], "demand_level": 5, "industries": ["tech", "software", "all"]},
    {"name": "Database Design", "category": "methodologies", "synonyms": ["database design", "schema design"], "demand_level": 4, "industries": ["tech", "software", "all"]},
    
    # Soft Skills
    {"name": "Leadership", "category": "soft_skills", "synonyms": ["leadership", "leading"], "demand_level": 5, "industries": ["all"]},
    {"name": "Communication", "category": "soft_skills", "synonyms": ["communication", "communicating"], "demand_level": 5, "industries": ["all"]},
    {"name": "Teamwork", "category": "soft_skills", "synonyms": ["teamwork", "collaboration"], "demand_level": 5, "industries": ["all"]},
    {"name": "Problem Solving", "category": "soft_skills", "synonyms": ["problem solving", "critical thinking"], "demand_level": 5, "industries": ["all"]},
    {"name": "Critical Thinking", "category": "soft_skills", "synonyms": ["critical thinking", "analysis"], "demand_level": 5, "industries": ["all"]},
    {"name": "Creativity", "category": "soft_skills", "synonyms": ["creativity", "creative"], "demand_level": 4, "industries": ["design", "marketing", "innovation"]},
    {"name": "Adaptability", "category": "soft_skills", "synonyms": ["adaptability", "flexible"], "demand_level": 5, "industries": ["all"]},
    {"name": "Time Management", "category": "soft_skills", "synonyms": ["time management", "organization"], "demand_level": 5, "industries": ["all"]},
    {"name": "Project Management", "category": "soft_skills", "synonyms": ["project management", "planning"], "demand_level": 5, "industries": ["all"]},
    {"name": "Analytical Skills", "category": "soft_skills", "synonyms": ["analytical", "analysis"], "demand_level": 5, "industries": ["all"]},
    {"name": "Attention to Detail", "category": "soft_skills", "synonyms": ["detail oriented", "attention to detail"], "demand_level": 5, "industries": ["all"]},
    {"name": "Multitasking", "category": "soft_skills", "synonyms": ["multitasking", "multitask"], "demand_level": 4, "industries": ["all"]},
    {"name": "Decision Making", "category": "soft_skills", "synonyms": ["decision making", "decisions"], "demand_level": 5, "industries": ["all"]},
    {"name": "Negotiation", "category": "soft_skills", "synonyms": ["negotiation", "negotiating"], "demand_level": 4, "industries": ["business", "sales", "management"]},
    {"name": "Presentation Skills", "category": "soft_skills", "synonyms": ["presentation", "public speaking"], "demand_level": 5, "industries": ["all"]},
    {"name": "Interpersonal Skills", "category": "soft_skills", "synonyms": ["interpersonal", "people skills"], "demand_level": 5, "industries": ["all"]},
    {"name": "Collaboration", "category": "soft_skills", "synonyms": ["collaboration", "teamwork"], "demand_level": 5, "industries": ["all"]},
    {"name": "Conflict Resolution", "category": "soft_skills", "synonyms": ["conflict resolution", "mediation"], "demand_level": 4, "industries": ["management", "hr", "all"]},
    {"name": "Mentoring", "category": "soft_skills", "synonyms": ["mentoring", "coaching"], "demand_level": 4, "industries": ["management", "leadership", "all"]},
    {"name": "Delegation", "category": "soft_skills", "synonyms": ["delegation", "delegating"], "demand_level": 4, "industries": ["management", "leadership"]},
    {"name": "Strategic Thinking", "category": "soft_skills", "synonyms": ["strategic thinking", "strategy"], "demand_level": 5, "industries": ["management", "leadership", "all"]},
    {"name": "Innovation", "category": "soft_skills", "synonyms": ["innovation", "innovative"], "demand_level": 4, "industries": ["tech", "research", "all"]},
    {"name": "Research Skills", "category": "soft_skills", "synonyms": ["research", "investigation"], "demand_level": 4, "industries": ["research", "academia", "all"]},
    {"name": "Writing Skills", "category": "soft_skills", "synonyms": ["writing", "documentation"], "demand_level": 5, "industries": ["all"]},
    {"name": "Customer Service", "category": "soft_skills", "synonyms": ["customer service", "client relations"], "demand_level": 4, "industries": ["service", "sales", "all"]},
    {"name": "Sales Skills", "category": "soft_skills", "synonyms": ["sales", "selling"], "demand_level": 4, "industries": ["sales", "business", "all"]},
    
    # Business Skills
    {"name": "Business Analysis", "category": "business_skills", "synonyms": ["business analysis", "ba"], "demand_level": 4, "industries": ["business", "tech", "finance"]},
    {"name": "Business Intelligence", "category": "business_skills", "synonyms": ["bi", "business intelligence"], "demand_level": 4, "industries": ["business", "data", "tech"]},
    {"name": "Data Analysis", "category": "business_skills", "synonyms": ["data analysis", "analytics"], "demand_level": 5, "industries": ["business", "tech", "all"]},
    {"name": "Financial Analysis", "category": "business_skills", "synonyms": ["financial analysis", "finance"], "demand_level": 4, "industries": ["finance", "business", "all"]},
    {"name": "Marketing", "category": "business_skills", "synonyms": ["marketing", "digital marketing"], "demand_level": 4, "industries": ["marketing", "business", "all"]},
    {"name": "Product Management", "category": "business_skills", "synonyms": ["product management", "product"], "demand_level": 5, "industries": ["tech", "business", "all"]},
    {"name": "Strategic Planning", "category": "business_skills", "synonyms": ["strategic planning", "strategy"], "demand_level": 5, "industries": ["management", "business", "all"]},
    {"name": "Risk Management", "category": "business_skills", "synonyms": ["risk management", "risk"], "demand_level": 4, "industries": ["finance", "insurance", "all"]},
    {"name": "Quality Management", "category": "business_skills", "synonyms": ["quality management", "quality"], "demand_level": 4, "industries": ["manufacturing", "tech", "all"]},
    {"name": "Process Improvement", "category": "business_skills", "synonyms": ["process improvement", "optimization"], "demand_level": 4, "industries": ["operations", "business", "all"]},
    {"name": "Change Management", "category": "business_skills", "synonyms": ["change management", "organizational change"], "demand_level": 4, "industries": ["management", "hr", "all"]},
    {"name": "Vendor Management", "category": "business_skills", "synonyms": ["vendor management", "supplier relations"], "demand_level": 3, "industries": ["procurement", "business", "all"]},
    {"name": "Contract Management", "category": "business_skills", "synonyms": ["contract management", "contracts"], "demand_level": 3, "industries": ["legal", "business", "all"]},
    {"name": "Budget Management", "category": "business_skills", "synonyms": ["budget management", "budgeting"], "demand_level": 4, "industries": ["finance", "management", "all"]},
    {"name": "Resource Management", "category": "business_skills", "synonyms": ["resource management", "resource allocation"], "demand_level": 4, "industries": ["management", "operations", "all"]},
    {"name": "Stakeholder Management", "category": "business_skills", "synonyms": ["stakeholder management", "stakeholders"], "demand_level": 4, "industries": ["management", "business", "all"]},
    {"name": "Compliance", "category": "business_skills", "synonyms": ["compliance", "regulatory"], "demand_level": 4, "industries": ["finance", "healthcare", "all"]},
    {"name": "Audit", "category": "business_skills", "synonyms": ["audit", "auditing"], "demand_level": 3, "industries": ["finance", "accounting", "all"]},
    {"name": "Accounting", "category": "business_skills", "synonyms": ["accounting", "bookkeeping"], "demand_level": 4, "industries": ["finance", "business", "all"]},
    {"name": "Operations Management", "category": "business_skills", "synonyms": ["operations management", "operations"], "demand_level": 4, "industries": ["operations", "business", "all"]},
    {"name": "Supply Chain", "category": "business_skills", "synonyms": ["supply chain", "logistics"], "demand_level": 4, "industries": ["manufacturing", "retail", "all"]},
    {"name": "E-commerce", "category": "business_skills", "synonyms": ["ecommerce", "online retail"], "demand_level": 4, "industries": ["retail", "business", "all"]},
    
    # Design Skills
    {"name": "UI Design", "category": "design_skills", "synonyms": ["ui", "user interface"], "demand_level": 5, "industries": ["tech", "design", "all"]},
    {"name": "UX Design", "category": "design_skills", "synonyms": ["ux", "user experience"], "demand_level": 5, "industries": ["tech", "design", "all"]},
    {"name": "Graphic Design", "category": "design_skills", "synonyms": ["graphic design", "graphics"], "demand_level": 4, "industries": ["design", "marketing", "all"]},
    {"name": "Web Design", "category": "design_skills", "synonyms": ["web design"], "demand_level": 5, "industries": ["web", "tech", "design"]},
    {"name": "Mobile Design", "category": "design_skills", "synonyms": ["mobile design", "app design"], "demand_level": 4, "industries": ["mobile", "tech", "design"]},
    {"name": "Interaction Design", "category": "design_skills", "synonyms": ["interaction design", "ixd"], "demand_level": 4, "industries": ["design", "tech", "all"]},
    {"name": "Visual Design", "category": "design_skills", "synonyms": ["visual design", "visuals"], "demand_level": 4, "industries": ["design", "marketing", "all"]},
    {"name": "Product Design", "category": "design_skills", "synonyms": ["product design"], "demand_level": 4, "industries": ["design", "tech", "product"]},
    {"name": "Service Design", "category": "design_skills", "synonyms": ["service design"], "demand_level": 3, "industries": ["design", "business", "all"]},
    {"name": "Design Thinking", "category": "design_skills", "synonyms": ["design thinking"], "demand_level": 4, "industries": ["design", "innovation", "all"]},
    {"name": "Prototyping", "category": "design_skills", "synonyms": ["prototyping", "prototypes"], "demand_level": 4, "industries": ["design", "tech", "all"]},
    {"name": "Wireframing", "category": "design_skills", "synonyms": ["wireframing", "wireframes"], "demand_level": 4, "industries": ["design", "tech", "all"]},
    {"name": "User Research", "category": "design_skills", "synonyms": ["user research", "ux research"], "demand_level": 4, "industries": ["design", "tech", "all"]},
    {"name": "Usability Testing", "category": "design_skills", "synonyms": ["usability testing", "user testing"], "demand_level": 4, "industries": ["design", "tech", "all"]},
    {"name": "Information Architecture", "category": "design_skills", "synonyms": ["information architecture", "ia"], "demand_level": 3, "industries": ["design", "tech", "all"]},
    {"name": "Typography", "category": "design_skills", "synonyms": ["typography", "fonts"], "demand_level": 3, "industries": ["design", "publishing", "all"]},
    {"name": "Color Theory", "category": "design_skills", "synonyms": ["color theory", "colors"], "demand_level": 3, "industries": ["design", "art", "all"]},
    {"name": "Layout Design", "category": "design_skills", "synonyms": ["layout design", "layouts"], "demand_level": 4, "industries": ["design", "publishing", "all"]},
    {"name": "Brand Design", "category": "design_skills", "synonyms": ["brand design", "branding"], "demand_level": 4, "industries": ["design", "marketing", "all"]},
    {"name": "Motion Design", "category": "design_skills", "synonyms": ["motion design", "animation"], "demand_level": 3, "industries": ["design", "media", "all"]},
    {"name": "3D Design", "category": "design_skills", "synonyms": ["3d design", "3d modeling"], "demand_level": 3, "industries": ["gaming", "animation", "all"]},
    {"name": "Video Editing", "category": "design_skills", "synonyms": ["video editing", "video production"], "demand_level": 3, "industries": ["media", "marketing", "all"]},
    {"name": "Animation", "category": "design_skills", "synonyms": ["animation", "animating"], "demand_level": 3, "industries": ["media", "gaming", "all"]},
    
    # Certifications
    {"name": "AWS Certified", "category": "certifications", "synonyms": ["aws certification", "aws certified"], "demand_level": 5, "industries": ["tech", "cloud", "all"]},
    {"name": "Azure Certified", "category": "certifications", "synonyms": ["azure certification", "microsoft certified"], "demand_level": 5, "industries": ["tech", "cloud", "all"]},
    {"name": "Google Cloud Certified", "category": "certifications", "synonyms": ["gcp certification", "google certified"], "demand_level": 4, "industries": ["tech", "cloud", "all"]},
    {"name": "PMP", "category": "certifications", "synonyms": ["pmp", "project management professional"], "demand_level": 5, "industries": ["project management", "all"]},
    {"name": "CSM", "category": "certifications", "synonyms": ["csm", "certified scrum master"], "demand_level": 4, "industries": ["tech", "software", "all"]},
    {"name": "CSD", "category": "certifications", "synonyms": ["csd", "certified scrum developer"], "demand_level": 3, "industries": ["tech", "software", "all"]},
    {"name": "CSPO", "category": "certifications", "synonyms": ["cspo", "certified scrum product owner"], "demand_level": 4, "industries": ["tech", "software", "all"]},
    {"name": "Oracle Certified", "category": "certifications", "synonyms": ["oracle certification", "oracle certified"], "demand_level": 4, "industries": ["tech", "database", "all"]},
    {"name": "Java Certified", "category": "certifications", "synonyms": ["java certification", "oracle java"], "demand_level": 4, "industries": ["tech", "java", "all"]},
    {"name": "Python Certified", "category": "certifications", "synonyms": ["python certification", "pcep"], "demand_level": 4, "industries": ["tech", "python", "all"]},
    {"name": "Microsoft Certified", "category": "certifications", "synonyms": ["microsoft certification", "ms certified"], "demand_level": 4, "industries": ["tech", "microsoft", "all"]},
    {"name": "Google Certified", "category": "certifications", "synonyms": ["google certification", "google certified"], "demand_level": 4, "industries": ["tech", "google", "all"]},
    {"name": "Facebook Certified", "category": "certifications", "synonyms": ["facebook certification", "meta certified"], "demand_level": 3, "industries": ["marketing", "social", "all"]},
    {"name": "CCNA", "category": "certifications", "synonyms": ["ccna", "cisco certified"], "demand_level": 4, "industries": ["networking", "tech", "all"]},
    {"name": "CCNP", "category": "certifications", "synonyms": ["ccnp", "cisco certified"], "demand_level": 4, "industries": ["networking", "tech", "all"]},
    {"name": "MCSE", "category": "certifications", "synonyms": ["mcse", "microsoft certified"], "demand_level": 3, "industries": ["tech", "microsoft", "all"]},
    {"name": "RHCE", "category": "certifications", "synonyms": ["rhce", "red hat certified"], "demand_level": 4, "industries": ["tech", "linux", "all"]},
    {"name": "CompTIA A+", "category": "certifications", "synonyms": ["comptia a+", "a+ certification"], "demand_level": 3, "industries": ["tech", "it", "all"]},
    {"name": "CompTIA Network+", "category": "certifications", "synonyms": ["comptia network+", "network+ certification"], "demand_level": 4, "industries": ["tech", "networking", "all"]},
    {"name": "CompTIA Security+", "category": "certifications", "synonyms": ["comptia security+", "security+ certification"], "demand_level": 4, "industries": ["tech", "security", "all"]},
    {"name": "CISSP", "category": "certifications", "synonyms": ["cissp", "certified information systems security professional"], "demand_level": 5, "industries": ["security", "tech", "all"]},
    {"name": "CEH", "category": "certifications", "synonyms": ["ceh", "certified ethical hacker"], "demand_level": 4, "industries": ["security", "tech", "all"]},
    {"name": "Tableau Certified", "category": "certifications", "synonyms": ["tableau certification", "tableau certified"], "demand_level": 4, "industries": ["data", "analytics", "all"]},
    {"name": "Power BI Certified", "category": "certifications", "synonyms": ["power bi certification", "microsoft bi"], "demand_level": 4, "industries": ["data", "analytics", "all"]},
    {"name": "Salesforce Certified", "category": "certifications", "synonyms": ["salesforce certification", "salesforce certified"], "demand_level": 4, "industries": ["crm", "business", "all"]},
    {"name": "SAP Certified", "category": "certifications", "synonyms": ["sap certification", "sap certified"], "demand_level": 4, "industries": ["erp", "business", "all"]},
    {"name": "Adobe Certified", "category": "certifications", "synonyms": ["adobe certification", "adobe certified"], "demand_level": 3, "industries": ["design", "creative", "all"]},
    {"name": "Autodesk Certified", "category": "certifications", "synonyms": ["autodesk certification", "autodesk certified"], "demand_level": 3, "industries": ["design", "engineering", "all"]},
    {"name": "PMI-ACP", "category": "certifications", "synonyms": ["pmi-acp", "agile certified practitioner"], "demand_level": 4, "industries": ["project management", "agile", "all"]},
    {"name": "ITIL Foundation", "category": "certifications", "synonyms": ["itil", "itil foundation"], "demand_level": 4, "industries": ["it", "service management", "all"]},
    {"name": "Six Sigma", "category": "certifications", "synonyms": ["six sigma", "lean six sigma"], "demand_level": 4, "industries": ["quality", "manufacturing", "all"]},
    {"name": "Lean Management", "category": "certifications", "synonyms": ["lean management", "lean certified"], "demand_level": 4, "industries": ["operations", "manufacturing", "all"]},
]

def get_skills_by_category(category):
    """Get all skills in a specific category"""
    return [skill for skill in COMPREHENSIVE_SKILLS_DATABASE if skill['category'] == category]

def get_all_skill_names():
    """Get all skill names for keyword matching"""
    all_names = []
    for skill in COMPREHENSIVE_SKILLS_DATABASE:
        all_names.append(skill['name'].lower())
        all_names.extend([synonym.lower() for synonym in skill['synonyms']])
    return list(set(all_names))

def get_skill_by_name(name):
    """Get skill details by name"""
    name_lower = name.lower()
    for skill in COMPREHENSIVE_SKILLS_DATABASE:
        if skill['name'].lower() == name_lower:
            return skill
        for synonym in skill['synonyms']:
            if synonym.lower() == name_lower:
                return skill
    return None

def get_high_demand_skills():
    """Get high demand skills (demand_level >= 4)"""
    return [skill for skill in COMPREHENSIVE_SKILLS_DATABASE if skill['demand_level'] >= 4]

def get_skills_by_industry(industry):
    """Get skills relevant to a specific industry"""
    industry_lower = industry.lower()
    return [skill for skill in COMPREHENSIVE_SKILLS_DATABASE 
            if industry_lower in [ind.lower() for ind in skill.get('industries', [])]]
