# Generated by Django 6.0.3 on 2026-04-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_career_savedcareer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionnaireanswer',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='savedcareer',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='careerrecommendation',
            name='user',
        ),
        migrations.AlterField(
            model_name='career',
            name='growth_rate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='career',
            name='required_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='career',
            name='salary_range',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='careerquestion',
            name='options',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='careerrecommendation',
            name='score',
            field=models.FloatField(),
        ),
        migrations.RemoveField(
            model_name='questionnaireanswer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='savedcareer',
            name='user',
        ),
    ]
