# Generated by Django 6.0.3 on 2026-04-14 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_alter_questionnaireanswer_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='careerrecommendation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaireanswer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedcareer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='career',
            name='growth_rate',
            field=models.CharField(help_text="e.g., '15% (Much faster than average)'", max_length=50),
        ),
        migrations.AlterField(
            model_name='career',
            name='required_skills',
            field=models.JSONField(blank=True, default=list, help_text='List of required skills'),
        ),
        migrations.AlterField(
            model_name='career',
            name='salary_range',
            field=models.CharField(help_text="e.g., '$60,000 - $80,000'", max_length=100),
        ),
        migrations.AlterField(
            model_name='careerquestion',
            name='options',
            field=models.JSONField(blank=True, default=dict, help_text='JSON object with options for choice questions'),
        ),
        migrations.AlterField(
            model_name='careerrecommendation',
            name='score',
            field=models.FloatField(help_text='Recommendation score from 0 to 100'),
        ),
        migrations.AlterUniqueTogether(
            name='questionnaireanswer',
            unique_together={('user', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='savedcareer',
            unique_together={('user', 'career')},
        ),
    ]
