# Generated by Django 6.0.3 on 2026-04-13 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_resumeupload_ai_confidence_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeupload',
            name='user',
        ),
    ]
